import type { NextPage } from 'next'
import { useState, useRef, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { ThemeBox } from '../dist/components/ThemeBox'
import { Interest } from '../dist/components/Interest'
import { interests } from '../dist/data'
import usePortfolioContext from '../dist/hooks/usePortfoliocontext'
import useVisible from '../dist/hooks/useVisible'
import styles from '../styles/Home.module.scss'
import img from '../public/images/oil.png'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const { themeStrings, menu } = usePortfolioContext()
  const router = useRouter()
  const imgRef = useRef(null)
  const isVisible = useVisible(imgRef, '-20%')
  
  return (
    <div className={menu && router.pathname === '/' ? [ styles.containerBlurred, styles.container ].join(' ') : styles.container}>
      <Head>
        <title>IamBram Front End Development</title>
        <meta name="Portfolio Front End Developer" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{/*-------------------------------- running theme ticker-------------------------------- */}
      <div className={ styles.themeTicker }>
        <div className={ styles.themeInner }>
            {   themeStrings.map((item: string) => 
                    <ThemeBox key={ item } item={ item }/>                               
                )
            }
        </div>
      </div>
{/*--------------------------------top section-------------------------------- */}
      <section className={[ styles.sectionOne, styles.section ].join(' ')}>
        <h1>
          Iam<br/>Bram
        </h1>
        <aside>
          Inquisitive + creative <br/>={'>'} Front End Development
        </aside>
        <div>
          <a download href='/BpvanZalk_CV.pdf' className={ styles.download }>
            Download my CV
          </a>
        </div>
      </section>
{/*--------------------------------qoute section-------------------------------- */}
      <section className={[ styles.sectionTwo, styles.section ].join(' ')}> 
        <div className={ styles.divOne }>
          <h3>Front end development</h3>
          <p>Please explore and see who I am and what I have to offer. </p>
        </div>
        <div className={ styles.divQoute }>
          <q><b>
          Great things come from hard work and perseverance.
          </b></q>
          <br/><br/>
          <q><b>
          No Excuses.
          </b></q>
          <br/><br/>
          <cite>Kobe Bryant</cite>
        </div>
      </section>
{/*--------------------------------oil image section-------------------------------- */}
      <section className={ styles.sectionThree }>
        <div className={ isVisible ? [styles.img, styles.imgLoaded].join(' ') : styles.img}  ref={ imgRef } >
          <Image
            src={ img }
            layout='responsive'
          />
        </div>
        <div className={ isVisible ? [styles.divOnImg, styles.divOnImgLoaded].join(' ') : styles.divOnImg}>
          What I love is most things associated with family, friends, good food and the outdoors.
          section about why, when, how learn to dev etc
        </div>
      </section>
{/*--------------------------------my important things section-------------------------------- */}
      <section className={ styles.sectionFour }>
        { interests.map(interest => 
          <Interest key={ interest.title } interest={ interest } /> 
        )}
      </section>
    </div>
  )
}

export default Home
